# Generated by Django 5.0.1 on 2024-01-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_category_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
